import type { PuEvent } from "@/lib/types";

export const MOCK_EVENTS: PuEvent[] = [
  {
    id: "uiuc-001",
    venueId: "venue-phi-kappa-psi",
    title: "ΦΚ Lawn Setup",
    category: "frat_party",
    categoryLabel: "Frat",
    area: "Gregory Dr",
    venueName: "Phi Kappa Psi",
    startsAt: "2026-05-08T21:30:00-05:00",
    endsAt: "2026-05-09T02:00:00-05:00",
    coverCents: 0,
    entryType: "free",
    stagRule: "Ratio til 11",
    ageRestriction: "18+",
    vibeMusic: "House / Jersey club",
    crowdStatus: "packed",
    urgencyLabels: ["Packed rn", "Line moving fast"],
    imageUrl:
      "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=900&q=80",
    imageAlt: "Crowd under purple lights at a party",
    heatScore: 98,
    liveNow: true,
    savesCount: 2840,
    spottingCount: 6200,
    pullUpsLastHour: 124,
    fillPressurePct: 91,
    campusTrendRank: 1,
    description:
      "Speakers already up on the lawn. Group chats say this is where people are shifting after Lion.",
    hostLabel: "Phi Kappa Psi Social",
    externalUrl: "https://instagram.com/explore/tags/uiuc/",
  },
  {
    id: "uiuc-002",
    venueId: "venue-joes-brewery",
    title: "Joe's Late Slice Run",
    category: "food_deal",
    categoryLabel: "Food",
    area: "Campustown",
    venueName: "Joe's Brewery",
    startsAt: "2026-05-08T22:00:00-05:00",
    endsAt: "2026-05-09T00:00:00-05:00",
    coverCents: null,
    entryType: "free",
    stagRule: "N/A",
    ageRestriction: "All ages",
    vibeMusic: "Bar noise / hip-hop",
    crowdStatus: "active",
    urgencyLabels: ["2-for-1 ends at midnight", "Post-bar rush"],
    imageUrl:
      "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=900&q=80",
    imageAlt: "Dim bar interior with bottles",
    heatScore: 86,
    liveNow: true,
    savesCount: 1520,
    spottingCount: 4100,
    pullUpsLastHour: 61,
    fillPressurePct: 72,
    campusTrendRank: 4,
    description:
      "Line picks up once KAMS starts thinning out. Quick food stop before the next move.",
    hostLabel: "Joe’s Brewery Campus",
    externalUrl: "https://www.joesbrewery.com/",
  },
  {
    id: "uiuc-003",
    venueId: "venue-kams",
    title: "KAMS Turkey Toss Watch Party",
    category: "watch_party",
    categoryLabel: "Watch party",
    area: "Green St",
    venueName: "KAM's",
    startsAt: "2026-05-08T20:00:00-05:00",
    endsAt: "2026-05-09T01:30:00-05:00",
    coverCents: 500,
    entryType: "cover",
    stagRule: "Open",
    ageRestriction: "19+",
    vibeMusic: "Country + stadium anthems",
    crowdStatus: "line_forming",
    urgencyLabels: ["Line forming", "Cover jumps at 10"],
    imageUrl:
      "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=900&q=80",
    imageAlt: "Sports fans cheering in a bar",
    heatScore: 91,
    liveNow: true,
    savesCount: 1980,
    spottingCount: 5500,
    pullUpsLastHour: 98,
    fillPressurePct: 84,
    campusTrendRank: 2,
    description:
      "Bar's loud early, then spills to the sidewalk before 10. If you're meeting friends, pull up now.",
    hostLabel: "KAM’s",
    externalUrl: "https://instagram.com/",
  },
  {
    id: "uiuc-004",
    venueId: "venue-isr-rooftop",
    title: "ISR Rooftop Mixer",
    category: "student_org",
    categoryLabel: "Student org",
    area: "ISR",
    venueName: "International Studies Rooftop",
    startsAt: "2026-05-08T19:00:00-05:00",
    endsAt: "2026-05-08T22:00:00-05:00",
    coverCents: null,
    entryType: "rsvp",
    stagRule: "School email",
    ageRestriction: "UIUC students",
    vibeMusic: "Afrobeats / pop",
    crowdStatus: "warming_up",
    urgencyLabels: ["Dead until 9", "RSVP closing"],
    imageUrl:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=900&q=80",
    imageAlt: "Outdoor concert lights at dusk",
    heatScore: 72,
    liveNow: false,
    savesCount: 640,
    spottingCount: 1800,
    pullUpsLastHour: 28,
    fillPressurePct: 58,
    campusTrendRank: 7,
    description:
      "Starts slower, then picks up once people finish dinner runs on Green.",
    hostLabel: "International Student Association × ISR Council",
    externalUrl: "https://illinois.edu/",
  },
  {
    id: "uiuc-005",
    venueId: "venue-canvas",
    title: "CANVAS Late Set",
    category: "bar_club",
    categoryLabel: "Club",
    area: "Downtown Champaign",
    venueName: "CANVAS",
    startsAt: "2026-05-08T22:30:00-05:00",
    endsAt: "2026-05-09T03:00:00-05:00",
    coverCents: 1000,
    entryType: "cover",
    stagRule: "Even ratio preferred",
    ageRestriction: "21+",
    vibeMusic: "Techno / melodic house",
    crowdStatus: "packed",
    urgencyLabels: ["Picked up after midnight", "Cover jumps at 11"],
    imageUrl:
      "https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=900&q=80",
    imageAlt: "Club lasers and dancing crowd",
    heatScore: 94,
    liveNow: true,
    savesCount: 3100,
    spottingCount: 8900,
    pullUpsLastHour: 156,
    fillPressurePct: 94,
    campusTrendRank: 3,
    description:
      "Downtown move once Campustown closes out. Usually the afters crowd lands here.",
    hostLabel: "CANVAS Nights",
    externalUrl: "https://instagram.com/explore/tags/champaign/",
  },
  {
    id: "uiuc-006",
    venueId: "venue-main-quad-south",
    title: "Quad Jazz & Chill Set",
    category: "campus",
    categoryLabel: "Campus",
    area: "Main Quad",
    venueName: "Main Quad South",
    startsAt: "2026-05-08T18:00:00-05:00",
    endsAt: "2026-05-08T21:00:00-05:00",
    coverCents: null,
    entryType: "free",
    stagRule: "Open",
    ageRestriction: "All ages",
    vibeMusic: "Live jazz",
    crowdStatus: "chill",
    urgencyLabels: ["Lowkey vibe", "Ends soon"],
    imageUrl:
      "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=900&q=80",
    imageAlt: "Musicians performing outdoors",
    heatScore: 54,
    liveNow: false,
    savesCount: 420,
    spottingCount: 960,
    pullUpsLastHour: 9,
    campusTrendRank: 12,
    description:
      "Soft pregame energy before everyone splits to bars or apartment pres.",
    hostLabel: "Illini Union Board × Jazz Society",
  },
  {
    id: "uiuc-007",
    venueId: "venue-red-lion",
    title: "Red Lion Karaoke",
    category: "bar_club",
    categoryLabel: "Bar",
    area: "Green St",
    venueName: "The Red Lion",
    startsAt: "2026-05-08T21:00:00-05:00",
    endsAt: "2026-05-09T00:30:00-05:00",
    coverCents: null,
    entryType: "free",
    stagRule: "Open",
    ageRestriction: "21+ after 9",
    vibeMusic: "Karaoke top hits",
    crowdStatus: "active",
    urgencyLabels: ["Line getting long", "Afters shifting later"],
    imageUrl:
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=900&q=80",
    imageAlt: "Microphone on stage with colorful lights",
    heatScore: 81,
    liveNow: true,
    savesCount: 1210,
    spottingCount: 3200,
    pullUpsLastHour: 44,
    fillPressurePct: 66,
    campusTrendRank: 5,
    description:
      "Crowd rotates all night here. People usually bounce from Lion to nearby afters around midnight.",
    hostLabel: "The Red Lion",
    externalUrl: "https://instagram.com/",
  },
  {
    id: "uiuc-008",
    venueId: "venue-siebel-atrium",
    title: "Siebel Atrium Pop-up",
    category: "pop_up",
    categoryLabel: "Pop-up",
    area: "Siebel Center",
    venueName: "Siebel Atrium",
    startsAt: "2026-05-08T17:30:00-05:00",
    endsAt: "2026-05-08T20:00:00-05:00",
    coverCents: null,
    entryType: "free",
    stagRule: "Student ID",
    ageRestriction: "Students",
    vibeMusic: "Lo-fi / chatter",
    crowdStatus: "warming_up",
    urgencyLabels: ["Free food moving fast"],
    imageUrl:
      "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=900&q=80",
    imageAlt: "Students mingling in a modern atrium",
    heatScore: 63,
    liveNow: false,
    savesCount: 510,
    spottingCount: 1200,
    pullUpsLastHour: 15,
    fillPressurePct: 41,
    description:
      "Quick student pop-up, mostly pregame energy before people head out.",
    hostLabel: "ACM @ UIUC",
    externalUrl: "https://acm.illinois.edu/",
  },
];

export function getEventById(id: string): PuEvent | undefined {
  return MOCK_EVENTS.find((e) => e.id === id);
}

/** Mock pulse totals for homepage hero strip */
export function getCampusPulseTotals(events: PuEvent[]): {
  liveVenues: number;
  pullUpsLastHour: number;
  spottingLive: number;
} {
  const live = events.filter((e) => e.liveNow);
  return {
    liveVenues: live.length,
    pullUpsLastHour: events.reduce((s, e) => s + e.pullUpsLastHour, 0),
    spottingLive: live.reduce((s, e) => s + e.spottingCount, 0),
  };
}

export function getHotEvents(events: PuEvent[], limit = 6): PuEvent[] {
  return [...events].sort((a, b) => b.heatScore - a.heatScore).slice(0, limit);
}
